server:
  port: 8086

spring:
  application:
    name: media-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/botmedia_media?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD:123456}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.botmedia.media.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:your-access-key-secret}
    bucket-name: ${ALIYUN_OSS_BUCKET:botmedia-files}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
